### PR TITLE
Update Fabric8 Kubernetes client to support Kubernetes v1 API

### PR DESCRIPTION
**Pull request by 3cky**
Currently Cellar Kubernetes discovery service is using Fabric8 client supporting deprecated `v1beta1` Kubernetes API. This patch updates Fabric8 Kubernetes client to version supporting latest Kubernetes `v1` API.

### CODE REVIEW

**Comment by jbonofre** [comment]
I created:

https://issues.apache.org/jira/browse/KARAF-3907

to track it.

Let me review and test.

Thanks !
Regards
JB

**Comment by jbonofre** [comment]
On Cellar master (4.0.0-SNAPSHOT), I'm already upgraded to Fabric8 feature 2.2.22 (latest one now), with latest kubernetes API. You can close this PR.

**Comment by 3cky** [comment]
Thanks! Please note, Fabric8 2.2.22 feature is not installable due to the inconsistency in export/imports:
```
> feature:install fabric8-kubernetes-api 
Refreshing bundles org.apache.karaf.webconsole.instance (539), org.apache.karaf.webconsole.http (542), org.apache.karaf.webconsole.gogo (541), org.apache.karaf.webconsole.features (540)
Error executing command: Can't install feature fabric8-kubernetes-api/0.0.0: 	
Could not start bundle mvn:io.fabric8/kubernetes-api/2.2.22 in feature(s) fabric8-kubernetes-api-2.2.22: Unresolved constraint in bundle io.fabric8.kubernetes-api [590]: Unable to resolve 590.0: missing requirement [590.0] osgi.wiring.package; (osgi.wiring.package=io.fabric8.openshift.client)
```
This bug is already fixed in master but version 2.2.23 still not released. :(

**Comment by 3cky** [comment]
Related commit: fabric8io/fabric8@25fbb977ef6a9a243ff1fafaa0f62a1f58e7ba2b

**Comment by jbonofre** [comment]
It looks to work on Karaf 4.0.0. Let me double check.

**Comment by 3cky** [comment]
Fabric8 updated to 2.2.23, and merged changes from master.

**Pull request merged**
